'use client'
import { motion } from 'framer-motion'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Map, Calendar, CheckCircle } from 'lucide-react'

interface Roadmap { id: string; title: string; goal: string; status: string; planJson: unknown; createdAt: Date }

export function RoadmapDetail({ roadmap }: { roadmap: Roadmap }) {
  const router = useRouter()
  const plan = roadmap.planJson as { steps?: { title: string; description: string; duration: string }[] } | null

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <button onClick={() => router.back()} className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mb-5 cursor-pointer">
        <ArrowLeft className="w-3.5 h-3.5" /> Back to roadmaps
      </button>
      <div className="flex items-start gap-4 mb-6">
        <div className="w-12 h-12 rounded-2xl bg-teal-500/10 border border-teal-500/20 flex items-center justify-center shrink-0">
          <Map className="w-6 h-6 text-teal-400" />
        </div>
        <div>
          <h1 className="text-xl font-extrabold text-foreground tracking-tight">{roadmap.title}</h1>
          <p className="text-sm text-muted-foreground mt-0.5">{roadmap.goal}</p>
          <div className="flex items-center gap-2 mt-2 text-[11px] text-muted-foreground/60">
            <Calendar className="w-3 h-3" />
            Created {new Date(roadmap.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
          </div>
        </div>
      </div>

      {plan?.steps ? (
        <div className="space-y-3">
          {plan.steps.map((step, i) => (
            <motion.div key={i} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.07 }}
              className="flex gap-4 rounded-xl border border-border bg-card p-4">
              <div className="flex flex-col items-center gap-1">
                <div className="w-7 h-7 rounded-full bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-xs font-bold text-teal-400 shrink-0">{i + 1}</div>
                {i < (plan.steps?.length ?? 0) - 1 && <div className="flex-1 w-px bg-border" />}
              </div>
              <div className="flex-1 pb-2">
                <div className="font-semibold text-sm text-foreground">{step.title}</div>
                <div className="text-[11.5px] text-muted-foreground mt-1 leading-relaxed">{step.description}</div>
                {step.duration && <div className="text-[10px] text-teal-400 mt-2 font-medium">{step.duration}</div>}
              </div>
            </motion.div>
          ))}
        </div>
      ) : (
        <div className="rounded-xl border border-border bg-card p-6 text-center text-sm text-muted-foreground">
          <CheckCircle className="w-8 h-8 mx-auto mb-3 text-muted-foreground/30" />
          Roadmap content will appear here once generated by the AI tool.
        </div>
      )}
    </div>
  )
}
