export const routes = {
  home: "/",
  pricing: "/pricing",
  features: "/features",
  featuresCareer: "/features/career",
  featuresLearning: "/features/learning",
  featuresTeams: "/features/teams",
  howItWorks: "/how-it-works",
  customers: "/customers",
  about: "/about",
  contact: "/contact",
  careers: "/careers",
  security: "/security",
  investors: "/investors",
  investorsDeck: "/investors/deck",
  investorsMarket: "/investors/market",
  investorsStrategy: "/investors/strategy",
  investorsArchitecture: "/investors/architecture",
  style: "/style",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
  cookies: "/legal/cookies",
} as const;

export type RouteKey = keyof typeof routes;
