import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { ramps, semantic } from "../lib/design/tokens/colors";
import { typeScale, fontFamily } from "../lib/design/tokens/typography";
import { space, layout } from "../lib/design/tokens/spacing";
import { radius } from "../lib/design/tokens/radius";
import { shadow, blur } from "../lib/design/tokens/shadows";
import { duration, easing } from "../lib/design/tokens/motion";
import { zIndex } from "../lib/design/tokens/zIndex";

const ref = (path: string) => {
  const [ramp, step] = path.split(".");
  return `var(--color-${ramp}-${step})`;
};

const lines: string[] = [];
lines.push("/* GENERATED by scripts/build-tokens.ts - do not edit. Run `npm run tokens`. */");

lines.push("@theme {");
for (const [name, r] of Object.entries(ramps)) {
  for (const [step, val] of Object.entries(r)) lines.push(`  --color-${name}-${step}: ${val};`);
}
lines.push(`  --font-sans: ${fontFamily.sans};`);
lines.push(`  --font-display: ${fontFamily.display};`);
lines.push(`  --font-data: ${fontFamily.data};`);
lines.push(`  --font-mono: ${fontFamily.mono};`);
for (const [k, v] of Object.entries(radius)) lines.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(shadow)) lines.push(`  --shadow-elevation-${k}: ${v};`);
for (const [k, v] of Object.entries(duration)) lines.push(`  --duration-${k}: ${v};`);
for (const [k, v] of Object.entries(easing)) lines.push(`  --ease-${k}: ${v};`);
for (const [k, v] of Object.entries(zIndex)) lines.push(`  --z-${k}: ${v};`);
for (const [k, v] of Object.entries(space)) lines.push(`  --spacing-${k}: ${v};`);
for (const [k, v] of Object.entries(layout)) lines.push(`  --layout-${k}: ${v};`);
lines.push(`  --blur-glass: ${blur.glass};`);
lines.push("}");

lines.push(":root {");
for (const [name, pair] of Object.entries(semantic)) lines.push(`  --${name}: ${ref(pair.light)};`);
lines.push("}");
lines.push(".dark {");
for (const [name, pair] of Object.entries(semantic)) lines.push(`  --${name}: ${ref(pair.dark)};`);
lines.push("}");

for (const [name, t] of Object.entries(typeScale)) {
  lines.push(`.text-${name} {`);
  lines.push(`  font-size: ${t.size}; line-height: ${t.line}; font-weight: ${t.weight}; letter-spacing: ${t.tracking}; font-family: var(--font-${t.family});`);
  if (name === "overline") lines.push("  text-transform: uppercase;");
  lines.push("}");
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = resolve(__dirname, "../app/styles/tokens.generated.css");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${out} (${lines.length} lines).`);
